### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by henrik1g** [Jarthianur/VFR-Backend#1]
Hey,

I was researching on how to build a standalone FLARM Radar using rtl-sdr and stumbled upon your project.
What is the correct command to build your source code? I could not find any of the make-cmake-style scripts I am used to. I (naively) tried gcc VFRB.cpp which resulted in lots of errors.

**Comment by Jarthianur** [comment]
Hi henrik1g,

I will add a makefile to this and update master and the docu asap.

The development on this project went so fast, that I did not concentrate on that yet.
But if you if you want to do it the naive way : 

> g++-4.9 -pthread -std=c++11 AircraftContainer.cpp Aircraft.cpp AircraftProcessor.cpp ConfigReader.cpp Configuration.cpp ConnectIn.cpp ConnectInExt.cpp Connection.cpp ConnectOutNMEA.cpp Main.cpp Math.cpp ParserAPRS.cpp Parser.cpp ParserSBS.cpp VFRB.cpp WeatherFeed.cpp

That is pretty ugly, but should work.

**Comment by henrik1g** [comment]
Thanks! Will try that later!
