### ISSUE TITLE
real GPS data instead of static

### ISSUE THREAD

**Issue by biturbo** [Jarthianur/VFR-Backend#22]
Is there also a function to use real GPS data stream instead of creating GGA and RMC for a static position ?

**Comment by rueckwaertsflieger** [comment]
Yes, definitely, I've tested and approved. VFR-B is the heart of a fully functional in-flight virtual radar receiver as well serving both, Flarm and ADS-B target processing.

**Comment by Jarthianur** [comment]
Hello
and thanks for being interested in this project.
**Yes, a dynamic GPS input is supported in the latest release.**
All You need is a GPS sensor and a server, like *gpsd*. If You got that setup running, simply add a feed entry in the VFRB config with the connection info to gpsd.

**Comment by biturbo** [comment]
strange as I have gpsd running with a 3D Fix but it is still taking the coordinates from the .ini file

[gps]
host = localhost
port = 2947

**Comment by Jarthianur** [comment]
Ok,
just to be sure I've tested this again and definitely got the values from gpsd and not the ones from the ini file.
Please check following points:
+ Your ini file has a parameter under [general] like "feeds=gps,..."
+ Just double check that gpsd is running and `cgps` reports a 3D fix
+ Look at the VFRB log; there must be these lines
    + (VFRB) run feed: gps
    + (GpsdClient) connected to: localhost:2947

If that doesn't solve it, please write me an email with the VFRB log and Your ini file as content and I'll have a look at it. But I think this is caused by a missing config. If You solve it on Your own, please report back, maybe I have to clearify the readme's a bit more.

**Comment by biturbo** [comment]
Hi,

Still no data from gpsd
Here the files and log

[INFO]  Mon Jun 26 06:33:57 2017:: VirtualFlightRadar-Backend -- 2.1.0
[ERROR] Mon Jun 26 06:33:57 2017:: (ConfigReader) malformed param [15]: gndMode    =
[ERROR] Mon Jun 26 06:33:57 2017:: (ConfigReader) malformed param [38]: maxHeight =
[ERROR] Mon Jun 26 06:33:57 2017:: (ConfigReader) malformed param [39]: maxDist   =
[INFO]  Mon Jun 26 06:33:57 2017:: (Config) latitude: 48.100000
[INFO]  Mon Jun 26 06:33:57 2017:: (Config) longitude: 8.850000
[INFO]  Mon Jun 26 06:33:57 2017:: (Config) altitude: 400
[INFO]  Mon Jun 26 06:33:57 2017:: (Config) geoid: 10.000000
[INFO]  Mon Jun 26 06:33:57 2017:: (Config) pressure: 1030.000000
[INFO]  Mon Jun 26 06:33:57 2017:: (Config) maxHeight: 2147483647
[INFO]  Mon Jun 26 06:33:57 2017:: (Config) maxDist: 2147483647
[INFO]  Mon Jun 26 06:33:57 2017:: (Config) serverPort: 2000
[INFO]  Mon Jun 26 06:33:57 2017:: (Config) number of feeds: 2
[INFO]  Mon Jun 26 06:33:57 2017:: (VFRB) GND mode: no
[INFO]  Mon Jun 26 06:33:57 2017:: (VFRB) startup
[INFO]  Mon Jun 26 06:33:57 2017:: (Server) startup: localhost 2000
[INFO]  Mon Jun 26 06:33:57 2017:: (VFRB) run feed: sbs
[INFO]  Mon Jun 26 06:33:57 2017:: (VFRB) run feed: gps
[INFO]  Mon Jun 26 06:33:57 2017:: (SbsClient) connected to: localhost:30003
[INFO]  Mon Jun 26 06:33:57 2017:: (GpsdClient) connected to: localhost:2947
[INFO]  Mon Jun 26 06:34:27 2017:: (Server) connection from: 192.168.1.11

Output port 2000
$GPRMC,065133,A,4806.00,N,00851.00,E,0,0,260617,001.0,W*65
$GPGGA,065133,4806.0000,N,00851.0000,E,1,05,1,400,M,10.0,M,,*47
$GPRMC,065134,A,4806.00,N,00851.00,E,0,0,260617,001.0,W*62
$GPGGA,065134,4806.0000,N,00851.0000,E,1,05,1,400,M,10.0,M,,*40
$GPRMC,065135,A,4806.00,N,00851.00,E,0,0,260617,001.0,W*63
$GPGGA,065135,4806.0000,N,00851.0000,E,1,05,1,400,M,10.0,M,,*41
$GPRMC,065136,A,4806.00,N,00851.00,E,0,0,260617,001.0,W*60
$GPGGA,065136,4806.0000,N,00851.0000,E,1,05,1,400,M,10.0,M,,*42
$PFLAU,,,,1,0,-178,0,3948,70836,3C5462*25
$PFLAA,0,-70779,-2842,3948,1,3C5462,,,,,8*0e
$GPRMC,065137,A,4806.00,N,00851.00,E,0,0,260617,001.0,W*61
$GPGGA,065137,4806.0000,N,00851.0000,E,1,05,1,400,M,10.0,M,,*43

[vfrb.zip](https://github.com/Jarthianur/VirtualFlightRadar-Backend/files/1101425/vfrb.zip)

![cgps](https://user-images.githubusercontent.com/12776429/27529943-bdd64154-5a56-11e7-9180-9edde27f688f.PNG)

**Comment by rueckwaertsflieger** [comment]
There is a bug with latest Pi+GPSD. GPSD sleeps unless a client tells GPSD to wake up. Make sure, GPSD is up and running. Invokoing connecting NTP or VFR-B is not sufficient. Try the following (Excerpt from the AMVR install guide)

"...
Now you have to apply a patch, as the Raspbian GPSD installation does not start GPSD at boot. GPSD waits for applications to connect to the gpsd.socket to start. Unfortunately NTP does not fulfill the GPSD run condition (neither does the –n option, telling gpsd as comes with Raspbian not to wait for client connects). Create a link 
`ln -s /lib/systemd/system/gpsd.service /etc/systemd/system/multi-user.target.wants/`
After, GPSD will start as expected. Now install hardware if you have not already done so. For details please refer to the hardware section.
..."
To see the difference:
Use `ps -aux | grep GPS` to verify GPSD status before above modification 1) right after boot and 2) after having invoked and exited cgps. Now make modification above, reboot. Then repeat steps 1) and 2) to see the difference.

**Comment by biturbo** [comment]
I had no difference in gpsd with this fix, gpsd was already running at start w/o any issues, no difference after creating the link same output 
pi        1171  0.0  0.2   4276  2016 pts/0    S+   11:46   0:00 grep --color=auto GPS

**Comment by rueckwaertsflieger** [comment]
If this is the only line, ps is reporting, it is reporting itself (as running), denoted by color=auto. GPSD is not running at all. Probably I forgot the sudo for creating the link. Did you verify, the link is existing in "/etc/systemd/system/multi-user.target.wants/" after executing the ln command? Try again with ln, preceeded by a sudo.
`sudo ln -s /lib/systemd/system/gpsd.service /etc/systemd/system/multi-user.target.wants/`

**Comment by biturbo** [comment]
I have executed it with sudo :-) and yes link is existing 

I use 
_GPSD_OPTIONS=" -n -b"_
in the /etc/default gpsd file

as an FYI

**Comment by rueckwaertsflieger** [comment]
I use Debian Jessie on Raspberry, last updated April 17. The GPSD standard package does go sleep for reasons of energy savings until a clients wakes it up. Not all clients do so!! Unfortunately, neither the START_DAEMON="true" command nor the -n option in GPSD's default file prevented GPSD from sleeping. That is, what the link given above corrected - in my case.

You cannot verify a GPSD sleeping with cgps, as this applictaion awakens the daemon. And again: If your ps command reports the only line given, GPSD is still sleeping.

As the log you gave suggests, VFR-B is connected to port 2947, I have no idea, what is missing. Try
`telnet localhost 2947` and follow the instructions given in http://www.catb.org/gpsd/installation.html , section 'how to test the software.'

**Comment by Jarthianur** [comment]
Ok Your config looks good so far, even the log says everything is working. The point is, that VFRB never receives any message from gpsd. As we figured out because Your gpsd is not running correctly. As rueckwaertsflieger correctly pointed out, the process You see from `ps aux | grep gpsd` is the grep process itself.
Note that cgps is an integrated tool, which uses the gpsd API and does not (afaik) connect to gpsd via TCP, as the VFRB does. Therefor cgps reports a 3D fix, but the gpsd server is not returning anything due to its eco-setup and configuration. To verify that do an  `telnet localhost 2947`, type `?WATCH={"enable":true,"nmea":true}` and hit enter. This is basically the same behavior to the VFRB and there should be no NMEA output.
But here is the config I use for gpsd, I modified it a bit some time ago (I think I had a similar issue due to newer version of gpsd)
```
$ cat /etc/default/gpsd
# Default settings for the gpsd init script and the hotplug wrapper.

# Start the gpsd daemon automatically at boot time
START_DAEMON="true"

# Use USB hotplugging to add new USB devices automatically to the daemon
USBAUTO="false"

# Devices gpsd should collect to at boot time.
# They need to be read/writeable, either by user gpsd or the group dialout.
DEVICES="/dev/ttyAMA0"

# Other options you want to pass to gpsd
GPSD_OPTIONS="-n -G"
GPSD_SOCKET="/var/run/gpsd.sock"

$ ls -la /etc/systemd/system/multi-user.target.wants/gpsd
lrwxrwxrwx  1 root root   32 Apr  2 18:34 gpsd.service -> /lib/systemd/system/gpsd.service

$ cat /etc/systemd/system/multi-user.target.wants/gpsd.service
[Unit]
Description=GPS (Global Positioning System) Daemon
Requires=gpsd.socket

[Service]
EnvironmentFile=-/etc/default/gpsd
ExecStart=/usr/sbin/gpsd -N $GPSD_OPTIONS $DEVICES

[Install]
Also=gpsd.socket
```
This hopefully should solve the issue with gpsd, at least this setup works 100% on my PI2 with latest Raspbian.
PS: As all those files are owned by root You need to prefix all writes and creations with `sudo`.

**Comment by biturbo** [comment]
okay just doing a clean installation with my RPi3 and latest Debian with your input, I have written a short install.sh on https://github.com/biturbo/VFRB-Install to automate the installation of DUMP1090, GPSD, VFRB, OGN and some smaller tweaks, will keep you posted

**Comment by biturbo** [comment]
so after a clean installation with my script it works.

pi@flightradar:~ $ ps aux | grep gpsd
gpsd       535  0.5  0.7  22116  7420 ?        S<sl 18:24   0:05 /usr/sbin/gpsd -N -n -G /dev/ttyAMA0
pi        1051  0.0  0.2   4276  1952 pts/0    S+   18:42   0:00 grep --color=auto gpsd

thanks for your help, will now do some tests with SkyDemon checking if I can see the ADSB and FLARM targets.

**Comment by Jarthianur** [comment]
Nice,
I think the `-G` flag was the essential one here according to [gpsd docs](http://www.catb.org/gpsd/).
Just had a quick look at Your install.sh, honestly to automate as much as possible is something we wanted to add in the near future too, but we had a lot of other things to get to work. We even thought about providing a complete image.
Maybe You can communicate with rueckwaertsflieger about that scripts, to deploy them in the AMVR, as they are a great step in the right direction.
